// Seed the on-chain registry for the demo: register each badge's consent
// record (badge key = owner, deployer pays rent) and the camera audit log.
// Idempotent: existing records are left alone unless `--reset` is passed, in
// which case their consent is set back to the seed value (owner-signed).
// Also writes capture-app/public/demo/badges.json so the operator panel can
// sign as each badge owner during the demo (devnet demo keys only).
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import {
  APP_DEMO_KEYS, CLUSTER, RELAYER_KEY_PATH, RPC_URL, addr, badgeKeyPath, cameraKeyPath, client, deployerKeypair,
  ensureFunded, ensureKeypair, keypairSigner, readSeed, topUp, tx,
} from "./_env.mts";

const reset = process.argv.includes("--reset");
const seed = readSeed();
const { conn, reg } = client();
const deployer = deployerKeypair();
const payer = keypairSigner(deployer);

console.log(`cluster ${CLUSTER}  rpc ${RPC_URL}`);
console.log(`program  ${reg.programId.toBase58()}  ${addr(reg.programId)}`);
console.log(`deployer ${deployer.publicKey.toBase58()}`);
const bal = await ensureFunded(conn, deployer.publicKey, 0.2);
console.log(`balance  ${(bal / 1e9).toFixed(3)} SOL`);
if (bal < 0.05e9) throw new Error("deployer has no SOL — run `solana airdrop 1` (devnet) and retry");

const demoKeys: { badgeId: string; label: string; owner: string; secretKey: number[] }[] = [];

for (const b of seed.badges) {
  const kp = ensureKeypair(badgeKeyPath(b.badgeId));
  demoKeys.push({ badgeId: b.badgeId, label: b.label, owner: kp.publicKey.toBase58(), secretKey: Array.from(kp.secretKey) });
  const existing = await reg.fetchConsent(b.badgeId);
  if (!existing) {
    const sig = await reg.register(keypairSigner(kp), b.badgeId, b.consent, payer);
    console.log(`registered ${b.badgeId} consent=${b.consent} owner=${kp.publicKey.toBase58()}\n   ${tx(sig)}`);
  } else if (existing.owner !== kp.publicKey.toBase58()) {
    console.warn(`!! ${b.badgeId} is registered to a different owner (${existing.owner}); keys/ may be stale`);
  } else if (reset && existing.consent !== b.consent) {
    const sig = await reg.setConsent(keypairSigner(kp), b.badgeId, b.consent, payer);
    console.log(`reset ${b.badgeId} → consent=${b.consent}\n   ${tx(sig)}`);
  } else {
    console.log(`ok ${b.badgeId} consent=${existing.consent} rev=${existing.revision} (${addr(existing.address)})`);
  }
}

// camera authority (signs attest_capture) and the demo relayer (pays fees for
// badge-signed updates from the operator panel) are funded by the deployer.
const cam = ensureKeypair(cameraKeyPath(seed.cameraLabel));
if (await topUp(conn, deployer, cam.publicKey, 0.02, 0.05)) console.log(`funded camera ${cam.publicKey.toBase58()} with 0.05 SOL`);
const relayer = ensureKeypair(RELAYER_KEY_PATH);
if (await topUp(conn, deployer, relayer.publicKey, 0.05, 0.1)) console.log(`funded relayer ${relayer.publicKey.toBase58()} with 0.1 SOL`);
const existingCam = await reg.fetchCamera(cam.publicKey);
if (!existingCam) {
  const sig = await reg.registerCamera(keypairSigner(cam), seed.cameraLabel);
  console.log(`registered camera ${seed.cameraLabel} authority=${cam.publicKey.toBase58()}\n   ${tx(sig)}`);
} else {
  console.log(`ok camera ${existingCam.label} count=${existingCam.count} head=${existingCam.head.slice(0, 16)}…`);
}

mkdirSync(dirname(APP_DEMO_KEYS), { recursive: true });
writeFileSync(
  APP_DEMO_KEYS,
  JSON.stringify(
    {
      _warning: "DEVNET DEMO KEYS — generated by registry/client/scripts/seed.ts; never commit",
      cluster: CLUSTER,
      badges: demoKeys,
      relayer: { pubkey: relayer.publicKey.toBase58(), secretKey: Array.from(relayer.secretKey) },
    },
    null,
    2,
  ),
);
console.log(`wrote demo keys for the operator panel → ${APP_DEMO_KEYS}`);
